'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

// Supported languages
export type Language = 'en' | 'pt' | 'es'

// Language context type
interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

// Create context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translations object
const translations = {
  en: {
    // Header
    solutions: "Solutions",
    pricing: "Pricing",
    contact: "Contact",
    
    // Hero Section
    heroTitle: "Generate, Enhance & Grow",
    heroSubtitle: "Transform Your Digital Presence with AI-Powered Platform Solutions",
    heroDescription: "The complete digital platform solution for any business. From websites to mobile apps, analytics to automation—we help you build, optimize, and scale your digital presence.",
    
    // Hero Form
    formTitle: "Start Your Digital Transformation",
    emailPlaceholder: "Your email address",
    businessPlaceholder: "Business name",
    phonePlaceholder: "Phone number (optional)",
    ctaButton: "Get Free Platform Audit →",
    ctaButtonLoading: "Getting Started...",
    
    // Features Section
    featuresTitle: "Complete Digital Platform Solutions",
    featuresSubtitle: "Everything you need to build, enhance, and grow your digital presence. From concept to conversion, we've got you covered.",
    
    // Feature A
    featureATitle: "Website & App Development",
    featureADesc: "Create stunning, responsive websites and mobile applications that convert visitors into customers. Our AI-powered platform builds optimized digital experiences tailored to your business.",
    featureAItem1: "Custom website design",
    featureAItem2: "Mobile app development",
    featureAItem3: "E-commerce integration",
    
    // Feature B
    featureBTitle: "SEO & Digital Marketing",
    featureBDesc: "Boost your online visibility and drive qualified traffic to your platforms. Our comprehensive digital marketing strategies ensure your business gets found by the right customers.",
    featureBItem1: "Search engine optimization",
    featureBItem2: "Social media management",
    featureBItem3: "Content marketing strategy",
    
    // Feature C
    featureCTitle: "Analytics & Automation",
    featureCDesc: "Make data-driven decisions with comprehensive analytics and automate your business processes. Track performance, optimize conversions, and scale efficiently.",
    featureCItem1: "Real-time analytics dashboard",
    featureCItem2: "Marketing automation",
    featureCItem3: "Performance optimization",
    
    // Social Proof
    socialProofTitle: "Trusted by Businesses Across All Industries",
    testimonial1: "\"Apex Vista AI completely transformed our digital presence. Our new website and mobile app have increased our customer engagement by 400% and our online sales have tripled.\"",
    testimonial1Author: "Sarah J., E-commerce Business Owner",
    testimonial2: "\"The analytics dashboard gives us insights we never had before. We can now make data-driven decisions that have improved our ROI by 250%.\"",
    testimonial2Author: "Mike R., Professional Services",
    testimonial3: "\"From website to mobile app to marketing automation - everything works seamlessly together. Our digital platform now generates 60% of our total revenue.\"",
    testimonial3Author: "Lisa M., Local Restaurant Chain",
    trustBarText: "Powering digital growth for businesses across all sectors:",
    sector1: "Retail & E-commerce",
    sector2: "Healthcare & Wellness",
    sector3: "Financial Services",
    sector4: "Technology & SaaS",
    
    // Agency Section
    agencyTitle: "Scaling a Digital Agency or Enterprise?",
    agencySubtitle: "White-label our entire platform suite to service your clients. Become an Apex Vista AI Partner and offer comprehensive digital solutions.",
    agencyNamePlaceholder: "Your name",
    agencyEmailPlaceholder: "Email address",
    agencyCompanyPlaceholder: "Company name",
    agencyMessagePlaceholder: "Tell us about your agency and client portfolio",
    agencyButton: "Get Partnership Details & Demo →",
    agencyButtonLoading: "Sending Request...",
    
    // Footer
    footerDescription: "Complete digital platform solutions to generate, enhance, and grow your business online.",
    footerSolutions: "Solutions",
    websiteDevelopment: "Website Development",
    mobileAppsFooter: "Mobile Apps",
    digitalMarketing: "Digital Marketing",
    analyticsAutomation: "Analytics & Automation",
    company: "Company",
    contactFooter: "Contact",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    support: "Support",
    copyright: "© 2025 Apex Vista AI. All rights reserved.",
    businessPhone: "Business: +1 (850) 565-1031",
    email: "contact@apexvistaai.com",
    location: "Location",

    // Company Page
    companyPageTitle: "Samuel Dantas' Commitment to AI-Powered Growth",
    companyPageSubtitle: "Visionary Leadership",
    globalRootsTitle: "Global Roots, Global Reach",
    globalRootsText: "Born and raised in João Pessoa, PB, Brazil, Samuel brings a unique global perspective to technology. Moving to Maryland at the age of 12 fostered an incredible linguistic agility, making him professionally fluent in Portuguese, Spanish, and English. This deep multicultural understanding is leveraged daily to build intuitive, globally scalable AI solutions.",
    companyMission: "Our Mission",
    companyMissionText: "As the CEO of Apex Vista AI, Samuel is dedicated to one mission: equipping business owners with the transformative power of Artificial Intelligence to achieve unprecedented scale and efficiency.",
    companyJourney: "The Journey",
    companyJourneyText: "For over 20 years, Samuel has immersed himself in software development, a journey that began in high school AP programming classes and formalized with a degree in Computer Engineering. This long-standing passion evolved into a unique and disciplined expertise during his eight years of distinguished service in the United States Air Force.",
    companyMilitary: "From Fighter Jets to Global AI Systems",
    companyMilitaryText1: "As an Avionics Technician, Samuel worked on some of the world's most advanced computer systems, developing a proficiency for complex, mission-critical technology. Driven by his commitment to service, he pioneered the development and implementation of automated facility management systems within the Air Force.",
    companyMilitaryText2: "These high-impact systems quickly gained traction, being adopted and implemented across 10+ USAF bases worldwide, proving his ability to deliver scalable, reliable solutions that earn the trust of leadership, from Airmen Basic to Generals.",
    companyFocus: "Serving Businesses with Precision",
    companyFocusText1: "Today, Samuel leverages this military precision, advanced technical background, and AI proficiency to serve the American public through the private sector. His commitment is clear: to consult with and develop bespoke AI systems that drive growth, streamline operations, and enhance profitability for every client.",
    companyFocusText2: "This experience polished his skill in SaaS development and rapidly honed his proficiency in utilizing AI to build sophisticated automated systems.",
    companyEducation: "Education & Continuous Development",
    companyEducationCurrent: "Currently Enrolled",
    companyEducationCurrentText: "Liberty University, Masters of Divinity Degree (M.Div.)",
    companyEducation2025: "2025",
    companyEducation2025Text: "Embry-Riddle Aeronautical University, Bachelor of Science in Interdisciplinary Studies",
    companyEducation2019: "2019",
    companyEducation2019Text: "Community College of the Air Force (CCAF), Associate of Science in Avionics Technology",
    companyPersonal: "Personal Life",
    companyPersonalText: "When he is not focused on the future of AI, Samuel enjoys spending time with his wife, Pollyana, and their two beautiful children.",
    companyYearsSoftware: "Years in Software",
    companyYearsUSAF: "Years USAF Service",
    companyUSAFBases: "USAF Bases",
    companyMissionFocus: "Mission Focus",

    // Terms of Service Modal
    termsTitle: "Terms of Service",
    termsLastUpdated: "Last Updated: November 7, 2025",
    termsIntro: "These Terms of Service (\"Terms\") govern your use of the Apex Vista AI platform and services. By accessing or using our services, you agree to be bound by these Terms.",
    termsAcceptance: "1. Acceptance of Terms",
    termsAcceptanceText: "By accessing and using Apex Vista AI services, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.",
    termsService: "2. Service Description",
    termsServiceText: "Apex Vista AI provides AI-powered digital marketing solutions, including but not limited to:",
    termsServiceItem1: "Website development and optimization",
    termsServiceItem2: "Mobile application development",
    termsServiceItem3: "Digital marketing campaigns",
    termsServiceItem4: "Analytics and automation tools",
    termsServiceItem5: "AI strategy consultations",
    termsResponsibilities: "3. User Responsibilities",
    termsResponsibilitiesText: "As a user of our services, you agree to:",
    termsResponsibilitiesItem1: "Provide accurate and complete information when creating an account",
    termsResponsibilitiesItem2: "Maintain the security of your account credentials",
    termsResponsibilitiesItem3: "Use our services in compliance with all applicable laws and regulations",
    termsResponsibilitiesItem4: "Not engage in any activity that could harm or disrupt our services",
    termsResponsibilitiesItem5: "Respect intellectual property rights",
    termsPayment: "4. Payment Terms",
    termsPaymentText: "For paid services:",
    termsPaymentItem1: "Payment is due upon subscription or service agreement",
    termsPaymentItem2: "All fees are non-refundable unless otherwise specified",
    termsPaymentItem3: "We reserve the right to modify pricing with 30 days notice",
    termsPaymentItem4: "Failure to pay may result in service suspension or termination",
    termsIP: "5. Intellectual Property",
    termsIPText: "All content, features, and functionality of our services are owned by Apex Vista AI and are protected by copyright, trademark, and other intellectual property laws. You may not reproduce, distribute, or create derivative works without our express written permission.",
    termsPrivacy: "6. Privacy and Data Protection",
    termsPrivacyText: "Your privacy is important to us. Please review our Privacy Policy, which also governs your use of our services, to understand our practices regarding the collection and use of your information.",
    termsAvailability: "7. Service Availability",
    termsAvailabilityText: "We strive to maintain high service availability but do not guarantee uninterrupted access. We may perform maintenance, updates, or modifications that could temporarily affect service availability.",
    termsLiability: "8. Limitation of Liability",
    termsLiabilityText: "To the fullest extent permitted by law, Apex Vista AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly.",
    termsTermination: "9. Termination",
    termsTerminationText: "We may terminate or suspend your account and access to our services at our sole discretion, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.",
    termsGoverning: "10. Governing Law",
    termsGoverningText: "These Terms shall be governed by and construed in accordance with the laws of the State of Florida, without regard to its conflict of law provisions. Any disputes shall be resolved in the courts of Okaloosa County, Florida.",
    termsChanges: "11. Changes to Terms",
    termsChangesText: "We reserve the right to modify these Terms at any time. We will notify users of any material changes by posting the new Terms on our website or through email notification. Your continued use of our services after such modifications constitutes acceptance of the updated Terms.",
    termsContact: "12. Contact Information",
    termsContactText: "If you have any questions about these Terms, please contact us at:",
    termsContactEmail: "Email: contact@apexvistaai.com",
    termsContactPhone: "Phone: +1 (850) 565-1031",
    closeButton: "Close",

    // Privacy Policy Modal
    privacyTitle: "Privacy Policy",
    privacyLastUpdated: "Last Updated: November 7, 2025",
    privacyIntro: "This Privacy Policy governs the manner in which Apex Vista AI (\"we,\" \"us,\" or \"our\") collects, uses, maintains, and discloses your personal information when you use our website, subscribe to the \"Reach Booster\" Service, or book a \"FREE AI Strategy Session.\"",
    privacyAcceptance: "1. Acceptance and Agreement to Terms",
    privacyAcceptanceText: "By subscribing to the Service, booking a consultation, or otherwise accessing the Apex Vista AI platform, you signify your acceptance of this Privacy Policy. If you do not agree to this policy, please do not use our Service. Your continued use following the posting of changes will be deemed your acceptance of those changes.",
    privacyCollection: "2. Information We Collect",
    privacyCollectionText: "We collect information directly from you when you interact with our Service.",
    privacyDataOverview: "Data Collection Overview",
    privacyDataCategory: "Data Category",
    privacyWhatCollect: "What We Collect",
    privacyPurpose: "Purpose of Collection",
    privacyAccountData: "Account & Billing Data",
    privacyAccountDataDesc: "Email, Name, Password (encrypted), Business Name, Billing Address, Payment Information (via secure processor)",
    privacyAccountDataPurpose: "To provide the Service, process subscription fees, manage your account, and deliver essential customer support",
    privacyConsultationData: "Consultation Data",
    privacyConsultationDataDesc: "Phone Number, Specific Pain Points/Goals (from booking form)",
    privacyConsultationDataPurpose: "To schedule and personalize the FREE AI Strategy Session, ensuring the consultation provides the highest value",
    privacyVoluntaryData: "Voluntary Data",
    privacyVoluntaryDataDesc: "Industry/Niche",
    privacyVoluntaryDataPurpose: "To improve the accuracy and relevance of the content and analysis generated by our AI tools for you",
    privacyUsage: "3. Usage, AI Data, and Non-Personal Information",
    privacyUsageText: "We automatically collect data whenever you interact with our platform.",
    privacyAIUsage: "AI Usage Data:",
    privacyAIUsageText: "We collect data on which features are used, generation history (inputs and outputs), and frequency of tool use. This is collected to monitor and enforce the usage limit of the Reach Booster plan (50 assets/month) and to continuously train and improve the performance and accuracy of our underlying AI models.",
    privacyTechnical: "Technical Data:",
    privacyTechnicalText: "This includes IP addresses, browser information, and access times. This is used for platform security, maintenance, and technical troubleshooting.",
    privacyUse: "4. How We Use Collected Information",
    privacyUseText: "Apex Vista AI uses your personal identification information for the following specific purposes:",
    privacyUseItem1: "To Fulfill Service Obligations: To operate and maintain the core functionality of the Reach Booster Service and deliver custom solutions through On-Demand Development.",
    privacyUseItem2: "To Enhance and Personalize the User Experience: We use aggregated usage data to understand how our Subscribers utilize the platform, allowing us to prioritize feature development and improve AI model outputs.",
    privacyUseItem3: "To Send Communication: To send essential security alerts, password resets, and critical updates pertaining to your account. You can opt-out of marketing emails at any time via the unsubscribe link.",
    privacyUseItem4: "To Improve Customer Service: Information you provide helps us respond to support needs and technical requests more efficiently.",
    privacySharing: "5. Sharing and Disclosure of Information",
    privacySharingText: "We do not sell, trade, or rent Subscriber personal identification information to others for marketing purposes. We share your information only in the following limited circumstances:",
    privacySharingItem1: "Service Providers: We share data with trusted third-party vendors (e.g., payment processors, hosting services) necessary for the effective operation of the Service. These parties are contractually bound to keep your information confidential.",
    privacySharingItem2: "Legal Compliance: We will disclose information when required by law or judicial process, specifically including courts in Okaloosa County, Florida, to protect our rights or the rights of others, or to enforce our Terms and Conditions.",
    privacySharingItem3: "Business Transfers: If Apex Vista AI is involved in a merger, acquisition, or sale of assets, your data may be transferred as part of that transaction.",
    privacyRights: "6. Your Rights and Choices",
    privacyRightsItem1: "Access and Correction: You may review and update most of your account information directly in your dashboard.",
    privacyRightsItem2: "Marketing Opt-Out: You can unsubscribe from marketing emails at any time.",
    privacyRightsItem3: "Data Deletion (Right to be Forgotten): You may request that we delete your account and associated data, subject to mandatory retention periods for legal, tax, or regulatory purposes.",
    privacySecurity: "7. Data Security",
    privacySecurityText: "We implement reasonable physical, technical, and administrative security measures designed to protect your Personal Information. You are responsible for maintaining the confidentiality of your account password.",
    privacyChildren: "8. Children's Privacy",
    privacyChildrenText: "Our Service is not directed to individuals under the age of 18. We do not knowingly collect personal information from children under 18.",
    privacyChanges: "9. Changes to This Privacy Policy",
    privacyChangesText: "The Provider has the discretion to update this Privacy Policy at any time. We will notify you of any material changes by posting the new policy on our website or through an email notification.",

    // Pricing Page
    pricingTitle: "Low, Simple, Powerful Pricing",
    pricingSubtitle: "Choose the perfect solution for your business. Start with our core platform or get custom development tailored to your needs.",
    coreSolutionTitle: "The Core Solution",
    coreSolutionSubtitle: "Everything you need to automate and scale your business with AI",
    reachBoosterTitle: "Reach Booster Plan",
    reachBoosterSubtitle: "Perfect for solopreneurs, small business owners, and micro-agencies",
    mostPopular: "MOST POPULAR",
    perMonth: "per month",
    perYear: "per year",
    saveMonths: "Save 2 months!",
    coreAIAccess: "Core AI Access",
    featuresSupport: "Features & Support",
    subscribeNow: "Subscribe Now & Start Automating →",
    moneyBackGuarantee: "30-day money-back guarantee • Cancel anytime",
    premiumDevelopmentTitle: "Premium On-Demand Development",
    premiumDevelopmentSubtitle: "Get customized development and 1:1 time with our expert team. The only way to get fully tailored solutions for your unique business needs.",
    apexSolutionTitle: "Apex Solution Build",
    apexSolutionPrice: "Starts at $1,500",
    oneTimeFee: "(One-time fee)",
    apexSolutionDesc: "Initial Product Development: We scope, build, and deploy a brand-new, customized digital tool using our advanced AI engine.",
    featureEnhancementTitle: "Feature Enhancement",
    featureEnhancementPrice: "$400 - $1,200",
    featureEnhancementDesc: "Development of Upgrades: Add custom features to your existing Reach Booster platform, such as specific API integrations or proprietary reports.",
    requestCustomQuote: "Request a Custom Quote",
    fullName: "Full Name *",
    emailAddress: "Email Address *",
    companyName: "Company Name",
    projectDetails: "Project Details *",
    projectDetailsPlaceholder: "Describe your project requirements, goals, timeline, and any specific features you need...",
    requestQuote: "Request a Custom Quote →",
    sendingRequest: "Sending Request...",
    responseTime: "Response Time:",
    responseTimeDesc: "Custom quotes are typically provided within 48 hours. Complex projects may require a brief consultation call.",
    faqTitle: "Frequently Asked Questions",
    freeConsultationTitle: "FREE AI Strategy Session",
    freeConsultationDesc: "Get a personalized 30-minute session to understand the possibilities of the Apex Vista AI Engine for your specific business.",
    bookConsultation: "Book Your Free Consultation →",
    bookingSession: "Booking Your Session...",
    backToHome: "Back to Home",

    // Contact Page
    contactTitle: "Get in Touch",
    contactSubtitle: "Ready to transform your digital presence? Let's discuss how we can help your business grow with our AI-powered platform solutions.",
    contactInformation: "Contact Information",
    phone: "Phone",
    phoneAvailable: "Available Monday - Friday, 9 AM - 6 PM EST",
    emailResponse: "We'll respond within 24 hours",
    locationClick: "Click to see our location",
    socialMedia: "Social Media",
    followUs: "Follow us for updates and insights",
    businessHours: "Business Hours",
    mondayFriday: "Monday - Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    closed: "Closed",
    happyClients: "Happy Clients",
    projectsDelivered: "Projects Delivered",
    sendMessage: "Send us a Message",
    yourFullName: "Your full name",
    yourEmail: "your@email.com",
    companyOptional: "Your company name (optional)",
    messageLabel: "Message *",
    messagePlaceholder: "Tell us about your project, goals, or any questions you have...",
    sendMessageBtn: "Send Message →",
    sendingMessage: "Sending Message...",
    responseTimeContact: "We typically respond within 24 hours during business days. For urgent matters, please call us directly."
  },
  pt: {
    // Header
    solutions: "Soluções",
    pricing: "Preços",
    contact: "Contato",
    
    // Hero Section
    heroTitle: "Gere, Aprimore & Cresça",
    heroSubtitle: "Transforme Sua Presença Digital com Soluções de Plataforma Alimentadas por IA",
    heroDescription: "A solução completa de plataforma digital para qualquer negócio. De sites a aplicativos móveis, análises à automação—ajudamos você a construir, otimizar e escalar sua presença digital.",
    
    // Hero Form
    formTitle: "Inicie Sua Transformação Digital",
    emailPlaceholder: "Seu endereço de email",
    businessPlaceholder: "Nome da empresa",
    phonePlaceholder: "Número de telefone (opcional)",
    ctaButton: "Obter Auditoria Gratuita da Plataforma →",
    ctaButtonLoading: "Iniciando...",
    
    // Features Section
    featuresTitle: "Soluções Completas de Plataforma Digital",
    featuresSubtitle: "Tudo que você precisa para construir, aprimorar e expandir sua presença digital. Do conceito à conversão, nós cuidamos de tudo.",
    
    // Feature A
    featureATitle: "Desenvolvimento de Sites e Apps",
    featureADesc: "Crie sites e aplicativos móveis impressionantes e responsivos que convertem visitantes em clientes. Nossa plataforma alimentada por IA constrói experiências digitais otimizadas sob medida para seu negócio.",
    featureAItem1: "Design personalizado de site",
    featureAItem2: "Desenvolvimento de aplicativo móvel",
    featureAItem3: "Integração de e-commerce",
    
    // Feature B
    featureBTitle: "SEO e Marketing Digital",
    featureBDesc: "Aumente sua visibilidade online e direcione tráfego qualificado para suas plataformas. Nossas estratégias abrangentes de marketing digital garantem que seu negócio seja encontrado pelos clientes certos.",
    featureBItem1: "Otimização para mecanismos de busca",
    featureBItem2: "Gerenciamento de redes sociais",
    featureBItem3: "Estratégia de marketing de conteúdo",
    
    // Feature C
    featureCTitle: "Análises e Automação",
    featureCDesc: "Tome decisões baseadas em dados com análises abrangentes e automatize seus processos de negócio. Rastreie desempenho, otimize conversões e escale com eficiência.",
    featureCItem1: "Painel de análises em tempo real",
    featureCItem2: "Automação de marketing",
    featureCItem3: "Otimização de desempenho",
    
    // Social Proof
    socialProofTitle: "Confiado por Empresas de Todos os Setores",
    testimonial1: "\"A Apex Vista AI transformou completamente nossa presença digital. Nosso novo site e aplicativo móvel aumentaram nosso engajamento de clientes em 400% e nossas vendas online triplicaram.\"",
    testimonial1Author: "Sarah J., Proprietária de E-commerce",
    testimonial2: "\"O painel de análises nos dá insights que nunca tivemos antes. Agora podemos tomar decisões baseadas em dados que melhoraram nosso ROI em 250%.\"",
    testimonial2Author: "Mike R., Serviços Profissionais",
    testimonial3: "\"De site a aplicativo móvel até automação de marketing - tudo funciona perfeitamente junto. Nossa plataforma digital agora gera 60% de nossa receita total.\"",
    testimonial3Author: "Lisa M., Rede de Restaurantes Local",
    trustBarText: "Impulsionando o crescimento digital para empresas de todos os setores:",
    sector1: "Varejo e E-commerce",
    sector2: "Saúde e Bem-estar",
    sector3: "Serviços Financeiros",
    sector4: "Tecnologia e SaaS",
    
    // Agency Section
    agencyTitle: "Escalando uma Agência Digital ou Empresa?",
    agencySubtitle: "Marque em branco todo nosso conjunto de plataformas para atender seus clientes. Torne-se um Parceiro Apex Vista AI e ofereça soluções digitais abrangentes.",
    agencyNamePlaceholder: "Seu nome",
    agencyEmailPlaceholder: "Endereço de email",
    agencyCompanyPlaceholder: "Nome da empresa",
    agencyMessagePlaceholder: "Conte-nos sobre sua agência e portfólio de clientes",
    agencyButton: "Obter Detalhes da Parceria e Demo →",
    agencyButtonLoading: "Enviando Solicitação...",
    
    // Footer
    footerDescription: "Soluções completas de plataforma digital para gerar, aprimorar e expandir seu negócio online.",
    footerSolutions: "Soluções",
    websiteDevelopment: "Desenvolvimento de Sites",
    mobileAppsFooter: "Aplicativos Móveis",
    digitalMarketing: "Marketing Digital",
    analyticsAutomation: "Análises e Automação",
    company: "Empresa",
    contactFooter: "Contato",
    termsOfService: "Termos de Serviço",
    privacyPolicy: "Política de Privacidade",
    support: "Suporte",
    copyright: "© 2025 Apex Vista AI. Todos os direitos reservados.",
    businessPhone: "Empresa: +1 (850) 565-1031",
    email: "contact@apexvistaai.com",
    location: "Localização",

    // Company Page
    companyPageTitle: "Compromisso de Samuel Dantas com o Crescimento Impulsionado por IA",
    companyPageSubtitle: "Liderança Visionária",
    globalRootsTitle: "Raízes Globais, Alcance Global",
    globalRootsText: "Nascido e criado em João Pessoa, PB, Brasil, Samuel traz uma perspectiva global única para a tecnologia. Mudar-se para Maryland aos 12 anos fomentou uma agilidade linguística incrível, tornando-o profissionalmente fluente em português, espanhol e inglês. Esta compreensão multicultural profunda é aproveitada diariamente para construir soluções de IA intuitivas e globalmente escaláveis.",
    companyMission: "Nossa Missão",
    companyMissionText: "Como CEO da Apex Vista AI, Samuel se dedica a uma missão: equipar proprietários de empresas com o poder transformador da Inteligência Artificial para alcançar escala e eficiência sem precedentes.",
    companyJourney: "A Jornada",
    companyJourneyText: "Por mais de 20 anos, Samuel se imergiu no desenvolvimento de software, uma jornada que começou nas aulas de programação AP do ensino médio e se formalizou com um diploma em Engenharia da Computação. Esta paixão de longa data evoluiu para uma expertise única e disciplinada durante seus oito anos de serviço distinto na Força Aérea dos Estados Unidos.",
    companyMilitary: "De Caças a Sistemas de IA Globais",
    companyMilitaryText1: "Como Técnico em Aviônicos, Samuel trabalhou em alguns dos sistemas de computador mais avançados do mundo, desenvolvendo proficiência para tecnologia complexa e crítica para missões. Impulsionado por seu compromisso com o serviço, ele foi pioneiro no desenvolvimento e implementação de sistemas automatizados de gerenciamento de instalações dentro da Força Aérea.",
    companyMilitaryText2: "Esses sistemas de alto impacto rapidamente ganharam força, sendo adotados e implementados em mais de 10 bases da USAF em todo o mundo, provando sua capacidade de entregar soluções escaláveis e confiáveis que conquistam a confiança da liderança, desde Soldados Básicos até Generais.",
    companyFocus: "Servindo Empresas com Precisão",
    companyFocusText1: "Hoje, Samuel aproveita essa precisão militar, formação técnica avançada e proficiência em IA para servir o público americano através do setor privado. Seu compromisso é claro: consultar e desenvolver sistemas de IA sob medida que impulsionem o crescimento, otimizem operações e aumentem a lucratividade para cada cliente.",
    companyFocusText2: "Esta experiência aprimorou sua habilidade no desenvolvimento de SaaS e rapidamente aperfeiçoou sua proficiência em utilizar IA para construir sistemas automatizados sofisticados.",
    companyEducation: "Educação e Desenvolvimento Contínuo",
    companyEducationCurrent: "Atualmente Matriculado",
    companyEducationCurrentText: "Liberty University, Mestrado em Divindade (M.Div.)",
    companyEducation2025: "2025",
    companyEducation2025Text: "Embry-Riddle Aeronautical University, Bacharelado em Ciências em Estudos Interdisciplinares",
    companyEducation2019: "2019",
    companyEducation2019Text: "Community College of the Air Force (CCAF), Associado em Ciências em Tecnologia de Aviônicos",
    companyPersonal: "Vida Pessoal",
    companyPersonalText: "Quando não está focado no futuro da IA, Samuel gosta de passar tempo com sua esposa, Pollyana, e seus dois lindos filhos.",
    companyYearsSoftware: "Anos em Software",
    companyYearsUSAF: "Anos de Serviço USAF",
    companyUSAFBases: "Bases USAF",
    companyMissionFocus: "Foco na Missão",

    // Terms of Service Modal
    termsTitle: "Termos de Serviço",
    termsLastUpdated: "Última Atualização: 7 de novembro de 2025",
    termsIntro: "Estes Termos de Serviço (\"Termos\") regem o uso da plataforma e serviços da Apex Vista AI. Ao acessar ou usar nossos serviços, você concorda em estar vinculado a estes Termos.",
    termsAcceptance: "1. Aceitação dos Termos",
    termsAcceptanceText: "Ao acessar e usar os serviços da Apex Vista AI, você aceita e concorda em estar vinculado aos termos e provisões deste acordo. Se você não concordar em cumprir o acima, por favor não use este serviço.",
    termsService: "2. Descrição do Serviço",
    termsServiceText: "A Apex Vista AI fornece soluções de marketing digital alimentadas por IA, incluindo mas não limitado a:",
    termsServiceItem1: "Desenvolvimento e otimização de sites",
    termsServiceItem2: "Desenvolvimento de aplicações móveis",
    termsServiceItem3: "Campanhas de marketing digital",
    termsServiceItem4: "Ferramentas de análise e automação",
    termsServiceItem5: "Consultorias de estratégia de IA",
    termsResponsibilities: "3. Responsabilidades do Usuário",
    termsResponsibilitiesText: "Como usuário de nossos serviços, você concorda em:",
    termsResponsibilitiesItem1: "Fornecer informações precisas e completas ao criar uma conta",
    termsResponsibilitiesItem2: "Manter a segurança das credenciais de sua conta",
    termsResponsibilitiesItem3: "Usar nossos serviços em conformidade com todas as leis e regulamentos aplicáveis",
    termsResponsibilitiesItem4: "Não se envolver em qualquer atividade que possa prejudicar ou interromper nossos serviços",
    termsResponsibilitiesItem5: "Respeitar os direitos de propriedade intelectual",
    termsPayment: "4. Termos de Pagamento",
    termsPaymentText: "Para serviços pagos:",
    termsPaymentItem1: "O pagamento é devido na assinatura ou acordo de serviço",
    termsPaymentItem2: "Todas as taxas são não reembolsáveis, salvo especificação em contrário",
    termsPaymentItem3: "Reservamo-nos o direito de modificar os preços com aviso de 30 dias",
    termsPaymentItem4: "A falha no pagamento pode resultar em suspensão ou rescisão do serviço",
    termsIP: "5. Propriedade Intelectual",
    termsIPText: "Todo o conteúdo, recursos e funcionalidades de nossos serviços são de propriedade da Apex Vista AI e são protegidos por direitos autorais, marcas registradas e outras leis de propriedade intelectual. Você não pode reproduzir, distribuir ou criar trabalhos derivados sem nossa permissão expressa por escrito.",
    termsPrivacy: "6. Privacidade e Proteção de Dados",
    termsPrivacyText: "Sua privacidade é importante para nós. Por favor, revise nossa Política de Privacidade, que também rege o uso de nossos serviços, para entender nossas práticas sobre a coleta e uso de suas informações.",
    termsAvailability: "7. Disponibilidade do Serviço",
    termsAvailabilityText: "Nos esforçamos para manter alta disponibilidade do serviço, mas não garantimos acesso ininterrupto. Podemos realizar manutenção, atualizações ou modificações que podem afetar temporariamente a disponibilidade do serviço.",
    termsLiability: "8. Limitação de Responsabilidade",
    termsLiabilityText: "Na extensão máxima permitida por lei, a Apex Vista AI não será responsável por quaisquer danos indiretos, incidentais, especiais, consequenciais ou punitivos, ou qualquer perda de lucros ou receitas, sejam incorridos direta ou indiretamente.",
    termsTermination: "9. Rescisão",
    termsTerminationText: "Podemos rescindir ou suspender sua conta e acesso aos nossos serviços a nosso exclusivo critério, sem aviso prévio, por conduta que acreditamos violar estes Termos ou ser prejudicial a outros usuários, a nós ou a terceiros.",
    termsGoverning: "10. Lei Aplicável",
    termsGoverningText: "Estes Termos serão regidos e interpretados de acordo com as leis do Estado da Flórida, sem consideração às suas disposições de conflito de leis. Quaisquer disputas serão resolvidas nos tribunais do Condado de Okaloosa, Flórida.",
    termsChanges: "11. Alterações nos Termos",
    termsChangesText: "Reservamo-nos o direito de modificar estes Termos a qualquer momento. Notificaremos os usuários de quaisquer alterações materiais publicando os novos Termos em nosso site ou através de notificação por email. Seu uso continuado de nossos serviços após tais modificações constitui aceitação dos Termos atualizados.",
    termsContact: "12. Informações de Contato",
    termsContactText: "Se você tiver alguma dúvida sobre estes Termos, entre em contato conosco em:",
    termsContactEmail: "Email: contact@apexvistaai.com",
    termsContactPhone: "Telefone: +1 (850) 565-1031",
    closeButton: "Fechar",

    // Privacy Policy Modal
    privacyTitle: "Política de Privacidade",
    privacyLastUpdated: "Última Atualização: 7 de novembro de 2025",
    privacyIntro: "Esta Política de Privacidade rege a maneira pela qual a Apex Vista AI (\"nós\", \"nos\" ou \"nosso\") coleta, usa, mantém e divulga suas informações pessoais quando você usa nosso site, assina o Serviço \"Reach Booster\" ou agenda uma \"Sessão de Estratégia de IA GRATUITA\".",
    privacyAcceptance: "1. Aceitação e Concordância com os Termos",
    privacyAcceptanceText: "Ao assinar o Serviço, agendar uma consulta ou acessar a plataforma Apex Vista AI, você indica sua aceitação desta Política de Privacidade. Se você não concordar com esta política, por favor não use nosso Serviço. Seu uso continuado após a publicação de alterações será considerado sua aceitação dessas alterações.",
    privacyCollection: "2. Informações que Coletamos",
    privacyCollectionText: "Coletamos informações diretamente de você quando interage com nosso Serviço.",
    privacyDataOverview: "Visão Geral da Coleta de Dados",
    privacyDataCategory: "Categoria de Dados",
    privacyWhatCollect: "O que Coletamos",
    privacyPurpose: "Finalidade da Coleta",
    privacyAccountData: "Dados de Conta e Cobrança",
    privacyAccountDataDesc: "Email, Nome, Senha (criptografada), Nome da Empresa, Endereço de Cobrança, Informações de Pagamento (via processador seguro)",
    privacyAccountDataPurpose: "Para fornecer o Serviço, processar taxas de assinatura, gerenciar sua conta e entregar suporte essencial ao cliente",
    privacyConsultationData: "Dados de Consulta",
    privacyConsultationDataDesc: "Número de Telefone, Pontos de Dor/Objetivos Específicos (do formulário de agendamento)",
    privacyConsultationDataPurpose: "Para agendar e personalizar a Sessão de Estratégia de IA GRATUITA, garantindo que a consulta forneça o maior valor",
    privacyVoluntaryData: "Dados Voluntários",
    privacyVoluntaryDataDesc: "Indústria/Nicho",
    privacyVoluntaryDataPurpose: "Para melhorar a precisão e relevância do conteúdo e análise gerados por nossas ferramentas de IA para você",
    privacyUsage: "3. Uso, Dados de IA e Informações Não Pessoais",
    privacyUsageText: "Coletamos automaticamente dados sempre que você interage com nossa plataforma.",
    privacyAIUsage: "Dados de Uso de IA:",
    privacyAIUsageText: "Coletamos dados sobre quais recursos são usados, histórico de geração (entradas e saídas) e frequência de uso da ferramenta. Isso é coletado para monitorar e aplicar o limite de uso do plano Reach Booster (50 ativos/mês) e para treinar e melhorar continuamente o desempenho e precisão de nossos modelos de IA subjacentes.",
    privacyTechnical: "Dados Técnicos:",
    privacyTechnicalText: "Isso inclui endereços IP, informações do navegador e horários de acesso. Isso é usado para segurança da plataforma, manutenção e solução de problemas técnicos.",
    privacyUse: "4. Como Usamos as Informações Coletadas",
    privacyUseText: "A Apex Vista AI usa suas informações de identificação pessoal para os seguintes propósitos específicos:",
    privacyUseItem1: "Para Cumprir Obrigações de Serviço: Para operar e manter a funcionalidade principal do Serviço Reach Booster e entregar soluções personalizadas através do Desenvolvimento Sob Demanda.",
    privacyUseItem2: "Para Melhorar e Personalizar a Experiência do Usuário: Usamos dados de uso agregados para entender como nossos Assinantes utilizam a plataforma, permitindo-nos priorizar o desenvolvimento de recursos e melhorar as saídas do modelo de IA.",
    privacyUseItem3: "Para Enviar Comunicação: Para enviar alertas de segurança essenciais, redefinições de senha e atualizações críticas relacionadas à sua conta. Você pode cancelar a inscrição de emails de marketing a qualquer momento através do link de cancelamento.",
    privacyUseItem4: "Para Melhorar o Atendimento ao Cliente: As informações que você fornece nos ajudam a responder às necessidades de suporte e solicitações técnicas de forma mais eficiente.",
    privacySharing: "5. Compartilhamento e Divulgação de Informações",
    privacySharingText: "Não vendemos, trocamos ou alugamos informações de identificação pessoal do Assinante para outros para fins de marketing. Compartilhamos suas informações apenas nas seguintes circunstâncias limitadas:",
    privacySharingItem1: "Provedores de Serviço: Compartilhamos dados com fornecedores terceirizados confiáveis (por exemplo, processadores de pagamento, serviços de hospedagem) necessários para a operação eficaz do Serviço. Essas partes são contratualmente obrigadas a manter suas informações confidenciais.",
    privacySharingItem2: "Conformidade Legal: Divulgaremos informações quando exigido por lei ou processo judicial, especificamente incluindo tribunais no Condado de Okaloosa, Flórida, para proteger nossos direitos ou os direitos de outros, ou para fazer cumprir nossos Termos e Condições.",
    privacySharingItem3: "Transferências de Negócios: Se a Apex Vista AI estiver envolvida em uma fusão, aquisição ou venda de ativos, seus dados podem ser transferidos como parte dessa transação.",
    privacyRights: "6. Seus Direitos e Escolhas",
    privacyRightsItem1: "Acesso e Correção: Você pode revisar e atualizar a maioria das informações de sua conta diretamente em seu painel.",
    privacyRightsItem2: "Cancelamento de Marketing: Você pode cancelar a inscrição de emails de marketing a qualquer momento.",
    privacyRightsItem3: "Exclusão de Dados (Direito ao Esquecimento): Você pode solicitar que excluamos sua conta e dados associados, sujeito a períodos de retenção obrigatórios para fins legais, fiscais ou regulamentares.",
    privacySecurity: "7. Segurança de Dados",
    privacySecurityText: "Implementamos medidas de segurança físicas, técnicas e administrativas razoáveis projetadas para proteger suas Informações Pessoais. Você é responsável por manter a confidencialidade da senha de sua conta.",
    privacyChildren: "8. Privacidade de Crianças",
    privacyChildrenText: "Nosso Serviço não é direcionado a indivíduos menores de 18 anos. Não coletamos conscientemente informações pessoais de crianças menores de 18 anos.",
    privacyChanges: "9. Alterações nesta Política de Privacidade",
    privacyChangesText: "O Provedor tem a discrição de atualizar esta Política de Privacidade a qualquer momento. Notificaremos você de quaisquer alterações materiais publicando a nova política em nosso site ou através de uma notificação por email.",

    // Pricing Page
    pricingTitle: "Preços Baixos, Simples e Poderosos",
    pricingSubtitle: "Escolha a solução perfeita para seu negócio. Comece com nossa plataforma principal ou obtenha desenvolvimento personalizado sob medida para suas necessidades.",
    coreSolutionTitle: "A Solução Principal",
    coreSolutionSubtitle: "Tudo que você precisa para automatizar e escalar seu negócio com IA",
    reachBoosterTitle: "Plano Reach Booster",
    reachBoosterSubtitle: "Perfeito para empreendedores individuais, proprietários de pequenas empresas e micro-agências",
    mostPopular: "MAIS POPULAR",
    perMonth: "por mês",
    perYear: "por ano",
    saveMonths: "Economize 2 meses!",
    coreAIAccess: "Acesso Principal à IA",
    featuresSupport: "Recursos e Suporte",
    subscribeNow: "Assine Agora e Comece a Automatizar →",
    moneyBackGuarantee: "Garantia de devolução do dinheiro de 30 dias • Cancele a qualquer momento",
    premiumDevelopmentTitle: "Desenvolvimento Premium Sob Demanda",
    premiumDevelopmentSubtitle: "Obtenha desenvolvimento personalizado e tempo 1:1 com nossa equipe especializada. A única maneira de obter soluções totalmente adaptadas às suas necessidades comerciais únicas.",
    apexSolutionTitle: "Construção de Solução Apex",
    apexSolutionPrice: "A partir de $1.500",
    oneTimeFee: "(Taxa única)",
    apexSolutionDesc: "Desenvolvimento de Produto Inicial: Nós planejamos, construímos e implantamos uma ferramenta digital totalmente nova e personalizada usando nosso mecanismo de IA avançado.",
    featureEnhancementTitle: "Aprimoramento de Recursos",
    featureEnhancementPrice: "$400 - $1.200",
    featureEnhancementDesc: "Desenvolvimento de Atualizações: Adicione recursos personalizados à sua plataforma Reach Booster existente, como integrações de API específicas ou relatórios proprietários.",
    requestCustomQuote: "Solicitar Orçamento Personalizado",
    fullName: "Nome Completo *",
    emailAddress: "Endereço de Email *",
    companyName: "Nome da Empresa",
    projectDetails: "Detalhes do Projeto *",
    projectDetailsPlaceholder: "Descreva os requisitos do seu projeto, objetivos, cronograma e quaisquer recursos específicos que você precisa...",
    requestQuote: "Solicitar Orçamento Personalizado →",
    sendingRequest: "Enviando Solicitação...",
    responseTime: "Tempo de Resposta:",
    responseTimeDesc: "Orçamentos personalizados são normalmente fornecidos em 48 horas. Projetos complexos podem exigir uma breve chamada de consulta.",
    faqTitle: "Perguntas Frequentes",
    freeConsultationTitle: "Sessão de Estratégia de IA GRATUITA",
    freeConsultationDesc: "Obtenha uma sessão personalizada de 30 minutos para entender as possibilidades do Mecanismo Apex Vista AI para seu negócio específico.",
    bookConsultation: "Agende Sua Consulta Gratuita →",
    bookingSession: "Agendando Sua Sessão...",
    backToHome: "Voltar ao Início",

    // Contact Page
    contactTitle: "Entre em Contato",
    contactSubtitle: "Pronto para transformar sua presença digital? Vamos discutir como podemos ajudar seu negócio a crescer com nossas soluções de plataforma alimentadas por IA.",
    contactInformation: "Informações de Contato",
    phone: "Telefone",
    phoneAvailable: "Disponível Segunda - Sexta, 9h - 18h EST",
    emailResponse: "Responderemos em 24 horas",
    locationClick: "Clique para ver nossa localização",
    socialMedia: "Redes Sociais",
    followUs: "Siga-nos para atualizações e insights",
    businessHours: "Horário Comercial",
    mondayFriday: "Segunda - Sexta",
    saturday: "Sábado",
    sunday: "Domingo",
    closed: "Fechado",
    happyClients: "Clientes Satisfeitos",
    projectsDelivered: "Projetos Entregues",
    sendMessage: "Envie-nos uma Mensagem",
    yourFullName: "Seu nome completo",
    yourEmail: "seu@email.com",
    companyOptional: "Nome da sua empresa (opcional)",
    messageLabel: "Mensagem *",
    messagePlaceholder: "Conte-nos sobre seu projeto, objetivos ou quaisquer perguntas que você tenha...",
    sendMessageBtn: "Enviar Mensagem →",
    sendingMessage: "Enviando Mensagem...",
    responseTimeContact: "Normalmente respondemos em 24 horas durante os dias úteis. Para assuntos urgentes, ligue diretamente para nós."
  },
  es: {
    // Header
    solutions: "Soluciones",
    pricing: "Precios",
    contact: "Contacto",
    
    // Hero Section
    heroTitle: "Genera, Mejora & Crece",
    heroSubtitle: "Transforma Tu Presencia Digital con Soluciones de Plataforma Impulsadas por IA",
    heroDescription: "La solución completa de plataforma digital para cualquier negocio. Desde sitios web hasta aplicaciones móviles, análisis hasta automatización—te ayudamos a construir, optimizar y escalar tu presencia digital.",
    
    // Hero Form
    formTitle: "Inicia Tu Transformación Digital",
    emailPlaceholder: "Tu dirección de correo electrónico",
    businessPlaceholder: "Nombre del negocio",
    phonePlaceholder: "Número de teléfono (opcional)",
    ctaButton: "Obtener Auditoría Gratuita de Plataforma →",
    ctaButtonLoading: "Comenzando...",
    
    // Features Section
    featuresTitle: "Soluciones Completas de Plataforma Digital",
    featuresSubtitle: "Todo lo que necesitas para construir, mejorar y hacer crecer tu presencia digital. Desde el concepto hasta la conversión, te tenemos cubierto.",
    
    // Feature A
    featureATitle: "Desarrollo de Sitios Web y Apps",
    featureADesc: "Crea sitios web y aplicaciones móviles impresionantes y responsivos que convierten visitantes en clientes. Nuestra plataforma impulsada por IA construye experiencias digitales optimizadas adaptadas a tu negocio.",
    featureAItem1: "Diseño personalizado de sitio web",
    featureAItem2: "Desarrollo de aplicación móvil",
    featureAItem3: "Integración de comercio electrónico",
    
    // Feature B
    featureBTitle: "SEO y Marketing Digital",
    featureBDesc: "Aumenta tu visibilidad en línea y dirige tráfico calificado a tus plataformas. Nuestras estrategias integrales de marketing digital aseguran que tu negocio sea encontrado por los clientes correctos.",
    featureBItem1: "Optimización para motores de búsqueda",
    featureBItem2: "Gestión de redes sociales",
    featureBItem3: "Estrategia de marketing de contenidos",
    
    // Feature C
    featureCTitle: "Análisis y Automatización",
    featureCDesc: "Toma decisiones basadas en datos con análisis integrales y automatiza tus procesos de negocio. Rastrea el rendimiento, optimiza conversiones y escala eficientemente.",
    featureCItem1: "Panel de análisis en tiempo real",
    featureCItem2: "Automatización de marketing",
    featureCItem3: "Optimización de rendimiento",
    
    // Social Proof
    socialProofTitle: "Confiado por Empresas de Todas las Industrias",
    testimonial1: "\"Apex Vista AI transformó completamente nuestra presencia digital. Nuestro nuevo sitio web y aplicación móvil han aumentado nuestro compromiso de clientes en 400% y nuestras ventas en línea se han triplicado.\"",
    testimonial1Author: "Sarah J., Propietaria de E-commerce",
    testimonial2: "\"El panel de análisis nos da perspectivas que nunca tuvimos antes. Ahora podemos tomar decisiones basadas en datos que han mejorado nuestro ROI en 250%.\"",
    testimonial2Author: "Mike R., Servicios Profesionales",
    testimonial3: "\"Desde sitio web hasta aplicación móvil hasta automatización de marketing - todo funciona perfectamente junto. Nuestra plataforma digital ahora genera el 60% de nuestros ingresos totales.\"",
    testimonial3Author: "Lisa M., Cadena de Restaurantes Local",
    trustBarText: "Impulsando el crecimiento digital para empresas de todos los sectores:",
    sector1: "Comercio Minorista y E-commerce",
    sector2: "Salud y Bienestar",
    sector3: "Servicios Financieros",
    sector4: "Tecnología y SaaS",
    
    // Agency Section
    agencyTitle: "¿Escalando una Agencia Digital o Empresa?",
    agencySubtitle: "Marca blanca de todo nuestro conjunto de plataformas para servir a tus clientes. Conviértete en un Socio de Apex Vista AI y ofrece soluciones digitales integrales.",
    agencyNamePlaceholder: "Tu nombre",
    agencyEmailPlaceholder: "Dirección de correo electrónico",
    agencyCompanyPlaceholder: "Nombre de la empresa",
    agencyMessagePlaceholder: "Cuéntanos sobre tu agencia y portafolio de clientes",
    agencyButton: "Obtener Detalles de Asociación y Demo →",
    agencyButtonLoading: "Enviando Solicitud...",
    
    // Footer
    footerDescription: "Soluciones completas de plataforma digital para generar, mejorar y hacer crecer tu negocio en línea.",
    footerSolutions: "Soluciones",
    websiteDevelopment: "Desarrollo de Sitios Web",
    mobileAppsFooter: "Aplicaciones Móviles",
    digitalMarketing: "Marketing Digital",
    analyticsAutomation: "Análisis y Automatización",
    company: "Empresa",
    contactFooter: "Contacto",
    termsOfService: "Términos de Servicio",
    privacyPolicy: "Política de Privacidad",
    support: "Soporte",
    copyright: "© 2025 Apex Vista AI. Todos los derechos reservados.",
    businessPhone: "Empresa: +1 (850) 565-1031",
    email: "contact@apexvistaai.com",
    location: "Ubicación",

    // Company Page
    companyPageTitle: "Compromiso de Samuel Dantas con el Crecimiento Impulsado por IA",
    companyPageSubtitle: "Liderazgo Visionario",
    globalRootsTitle: "Raíces Globales, Alcance Global",
    globalRootsText: "Nacido y criado en João Pessoa, PB, Brasil, Samuel aporta una perspectiva global única a la tecnología. Mudarse a Maryland a los 12 años fomentó una agilidad lingüística increíble, haciéndolo profesionalmente fluido en portugués, español e inglés. Esta comprensión multicultural profunda se aprovecha diariamente para construir soluciones de IA intuitivas y globalmente escalables.",
    companyMission: "Nuestra Misión",
    companyMissionText: "Como CEO de Apex Vista AI, Samuel se dedica a una misión: equipar a los propietarios de empresas con el poder transformador de la Inteligencia Artificial para lograr una escala y eficiencia sin precedentes.",
    companyJourney: "El Viaje",
    companyJourneyText: "Durante más de 20 años, Samuel se ha sumergido en el desarrollo de software, un viaje que comenzó en las clases de programación AP de la escuela secundaria y se formalizó con un título en Ingeniería Informática. Esta pasión de larga data evolucionó hacia una experiencia única y disciplinada durante sus ocho años de servicio distinguido en la Fuerza Aérea de los Estados Unidos.",
    companyMilitary: "De Aviones de Combate a Sistemas de IA Globales",
    companyMilitaryText1: "Como Técnico en Aviónica, Samuel trabajó en algunos de los sistemas informáticos más avanzados del mundo, desarrollando competencia para tecnología compleja y crítica para misiones. Impulsado por su compromiso con el servicio, fue pionero en el desarrollo e implementación de sistemas automatizados de gestión de instalaciones dentro de la Fuerza Aérea.",
    companyMilitaryText2: "Estos sistemas de alto impacto rápidamente ganaron tracción, siendo adoptados e implementados en más de 10 bases de la USAF en todo el mundo, demostrando su capacidad para entregar soluciones escalables y confiables que se ganan la confianza del liderazgo, desde Aviadores Básicos hasta Generales.",
    companyFocus: "Sirviendo a las Empresas con Precisión",
    companyFocusText1: "Hoy, Samuel aprovecha esta precisión militar, formación técnica avanzada y competencia en IA para servir al público estadounidense a través del sector privado. Su compromiso es claro: consultar y desarrollar sistemas de IA personalizados que impulsen el crecimiento, optimicen las operaciones y mejoren la rentabilidad para cada cliente.",
    companyFocusText2: "Esta experiencia pulió su habilidad en el desarrollo de SaaS y rápidamente perfeccionó su competencia en utilizar IA para construir sistemas automatizados sofisticados.",
    companyEducation: "Educación y Desarrollo Continuo",
    companyEducationCurrent: "Actualmente Inscrito",
    companyEducationCurrentText: "Liberty University, Maestría en Divinidad (M.Div.)",
    companyEducation2025: "2025",
    companyEducation2025Text: "Embry-Riddle Aeronautical University, Licenciatura en Ciencias en Estudios Interdisciplinarios",
    companyEducation2019: "2019",
    companyEducation2019Text: "Community College of the Air Force (CCAF), Asociado en Ciencias en Tecnología de Aviónica",
    companyPersonal: "Vida Personal",
    companyPersonalText: "Cuando no está enfocado en el futuro de la IA, Samuel disfruta pasar tiempo con su esposa, Pollyana, y sus dos hermosos hijos.",
    companyYearsSoftware: "Años en Software",
    companyYearsUSAF: "Años de Servicio USAF",
    companyUSAFBases: "Bases USAF",
    companyMissionFocus: "Enfoque en la Misión",

    // Terms of Service Modal
    termsTitle: "Términos de Servicio",
    termsLastUpdated: "Última Actualización: 7 de noviembre de 2025",
    termsIntro: "Estos Términos de Servicio (\"Términos\") rigen el uso de la plataforma y servicios de Apex Vista AI. Al acceder o usar nuestros servicios, aceptas estar sujeto a estos Términos.",
    termsAcceptance: "1. Aceptación de Términos",
    termsAcceptanceText: "Al acceder y usar los servicios de Apex Vista AI, aceptas y acuerdas estar sujeto a los términos y disposiciones de este acuerdo. Si no aceptas cumplir con lo anterior, por favor no uses este servicio.",
    termsService: "2. Descripción del Servicio",
    termsServiceText: "Apex Vista AI proporciona soluciones de marketing digital impulsadas por IA, incluyendo pero no limitado a:",
    termsServiceItem1: "Desarrollo y optimización de sitios web",
    termsServiceItem2: "Desarrollo de aplicaciones móviles",
    termsServiceItem3: "Campañas de marketing digital",
    termsServiceItem4: "Herramientas de análisis y automatización",
    termsServiceItem5: "Consultas de estrategia de IA",
    termsResponsibilities: "3. Responsabilidades del Usuario",
    termsResponsibilitiesText: "Como usuario de nuestros servicios, aceptas:",
    termsResponsibilitiesItem1: "Proporcionar información precisa y completa al crear una cuenta",
    termsResponsibilitiesItem2: "Mantener la seguridad de las credenciales de tu cuenta",
    termsResponsibilitiesItem3: "Usar nuestros servicios en cumplimiento con todas las leyes y regulaciones aplicables",
    termsResponsibilitiesItem4: "No participar en ninguna actividad que pueda dañar o interrumpir nuestros servicios",
    termsResponsibilitiesItem5: "Respetar los derechos de propiedad intelectual",
    termsPayment: "4. Términos de Pago",
    termsPaymentText: "Para servicios pagados:",
    termsPaymentItem1: "El pago se debe al momento de la suscripción o acuerdo de servicio",
    termsPaymentItem2: "Todas las tarifas no son reembolsables a menos que se especifique lo contrario",
    termsPaymentItem3: "Nos reservamos el derecho de modificar los precios con 30 días de aviso",
    termsPaymentItem4: "El incumplimiento de pago puede resultar en suspensión o terminación del servicio",
    termsIP: "5. Propiedad Intelectual",
    termsIPText: "Todo el contenido, características y funcionalidad de nuestros servicios son propiedad de Apex Vista AI y están protegidos por derechos de autor, marcas registradas y otras leyes de propiedad intelectual. No puedes reproducir, distribuir o crear trabajos derivados sin nuestro permiso expreso por escrito.",
    termsPrivacy: "6. Privacidad y Protección de Datos",
    termsPrivacyText: "Tu privacidad es importante para nosotros. Por favor revisa nuestra Política de Privacidad, que también rige el uso de nuestros servicios, para entender nuestras prácticas sobre la recopilación y uso de tu información.",
    termsAvailability: "7. Disponibilidad del Servicio",
    termsAvailabilityText: "Nos esforzamos por mantener alta disponibilidad del servicio pero no garantizamos acceso ininterrumpido. Podemos realizar mantenimiento, actualizaciones o modificaciones que podrían afectar temporalmente la disponibilidad del servicio.",
    termsLiability: "8. Limitación de Responsabilidad",
    termsLiabilityText: "En la máxima medida permitida por la ley, Apex Vista AI no será responsable de ningún daño indirecto, incidental, especial, consecuencial o punitivo, o cualquier pérdida de ganancias o ingresos, ya sea incurrido directa o indirectamente.",
    termsTermination: "9. Terminación",
    termsTerminationText: "Podemos terminar o suspender tu cuenta y acceso a nuestros servicios a nuestra sola discreción, sin previo aviso, por conducta que creemos viola estos Términos o es dañina para otros usuarios, nosotros o terceros.",
    termsGoverning: "10. Ley Aplicable",
    termsGoverningText: "Estos Términos se regirán e interpretarán de acuerdo con las leyes del Estado de Florida, sin consideración a sus disposiciones de conflicto de leyes. Cualquier disputa se resolverá en los tribunales del Condado de Okaloosa, Florida.",
    termsChanges: "11. Cambios en los Términos",
    termsChangesText: "Nos reservamos el derecho de modificar estos Términos en cualquier momento. Notificaremos a los usuarios de cualquier cambio material publicando los nuevos Términos en nuestro sitio web o a través de notificación por correo electrónico. Tu uso continuado de nuestros servicios después de tales modificaciones constituye aceptación de los Términos actualizados.",
    termsContact: "12. Información de Contacto",
    termsContactText: "Si tienes alguna pregunta sobre estos Términos, por favor contáctanos en:",
    termsContactEmail: "Correo: contact@apexvistaai.com",
    termsContactPhone: "Teléfono: +1 (850) 565-1031",
    closeButton: "Cerrar",

    // Privacy Policy Modal
    privacyTitle: "Política de Privacidad",
    privacyLastUpdated: "Última Actualización: 7 de noviembre de 2025",
    privacyIntro: "Esta Política de Privacidad rige la manera en que Apex Vista AI (\"nosotros\", \"nos\" o \"nuestro\") recopila, usa, mantiene y divulga tu información personal cuando usas nuestro sitio web, te suscribes al Servicio \"Reach Booster\" o reservas una \"Sesión de Estrategia de IA GRATUITA\".",
    privacyAcceptance: "1. Aceptación y Acuerdo con los Términos",
    privacyAcceptanceText: "Al suscribirte al Servicio, reservar una consulta o acceder de otra manera a la plataforma Apex Vista AI, indicas tu aceptación de esta Política de Privacidad. Si no estás de acuerdo con esta política, por favor no uses nuestro Servicio. Tu uso continuado después de la publicación de cambios se considerará tu aceptación de esos cambios.",
    privacyCollection: "2. Información que Recopilamos",
    privacyCollectionText: "Recopilamos información directamente de ti cuando interactúas con nuestro Servicio.",
    privacyDataOverview: "Resumen de Recopilación de Datos",
    privacyDataCategory: "Categoría de Datos",
    privacyWhatCollect: "Qué Recopilamos",
    privacyPurpose: "Propósito de la Recopilación",
    privacyAccountData: "Datos de Cuenta y Facturación",
    privacyAccountDataDesc: "Correo, Nombre, Contraseña (encriptada), Nombre del Negocio, Dirección de Facturación, Información de Pago (vía procesador seguro)",
    privacyAccountDataPurpose: "Para proporcionar el Servicio, procesar tarifas de suscripción, gestionar tu cuenta y entregar soporte esencial al cliente",
    privacyConsultationData: "Datos de Consulta",
    privacyConsultationDataDesc: "Número de Teléfono, Puntos de Dolor/Objetivos Específicos (del formulario de reserva)",
    privacyConsultationDataPurpose: "Para programar y personalizar la Sesión de Estrategia de IA GRATUITA, asegurando que la consulta proporcione el mayor valor",
    privacyVoluntaryData: "Datos Voluntarios",
    privacyVoluntaryDataDesc: "Industria/Nicho",
    privacyVoluntaryDataPurpose: "Para mejorar la precisión y relevancia del contenido y análisis generados por nuestras herramientas de IA para ti",
    privacyUsage: "3. Uso, Datos de IA e Información No Personal",
    privacyUsageText: "Recopilamos automáticamente datos cada vez que interactúas con nuestra plataforma.",
    privacyAIUsage: "Datos de Uso de IA:",
    privacyAIUsageText: "Recopilamos datos sobre qué características se usan, historial de generación (entradas y salidas) y frecuencia de uso de herramientas. Esto se recopila para monitorear y hacer cumplir el límite de uso del plan Reach Booster (50 activos/mes) y para entrenar y mejorar continuamente el rendimiento y precisión de nuestros modelos de IA subyacentes.",
    privacyTechnical: "Datos Técnicos:",
    privacyTechnicalText: "Esto incluye direcciones IP, información del navegador y tiempos de acceso. Esto se usa para seguridad de la plataforma, mantenimiento y solución de problemas técnicos.",
    privacyUse: "4. Cómo Usamos la Información Recopilada",
    privacyUseText: "Apex Vista AI usa tu información de identificación personal para los siguientes propósitos específicos:",
    privacyUseItem1: "Para Cumplir Obligaciones de Servicio: Para operar y mantener la funcionalidad central del Servicio Reach Booster y entregar soluciones personalizadas a través del Desarrollo Bajo Demanda.",
    privacyUseItem2: "Para Mejorar y Personalizar la Experiencia del Usuario: Usamos datos de uso agregados para entender cómo nuestros Suscriptores utilizan la plataforma, permitiéndonos priorizar el desarrollo de características y mejorar las salidas del modelo de IA.",
    privacyUseItem3: "Para Enviar Comunicación: Para enviar alertas de seguridad esenciales, restablecimientos de contraseña y actualizaciones críticas relacionadas con tu cuenta. Puedes cancelar la suscripción a correos de marketing en cualquier momento a través del enlace de cancelación.",
    privacyUseItem4: "Para Mejorar el Servicio al Cliente: La información que proporcionas nos ayuda a responder a las necesidades de soporte y solicitudes técnicas de manera más eficiente.",
    privacySharing: "5. Compartir y Divulgación de Información",
    privacySharingText: "No vendemos, intercambiamos o alquilamos información de identificación personal del Suscriptor a otros para propósitos de marketing. Compartimos tu información solo en las siguientes circunstancias limitadas:",
    privacySharingItem1: "Proveedores de Servicios: Compartimos datos con proveedores terceros confiables (ej., procesadores de pago, servicios de hosting) necesarios para la operación efectiva del Servicio. Estas partes están contractualmente obligadas a mantener tu información confidencial.",
    privacySharingItem2: "Cumplimiento Legal: Divulgaremos información cuando sea requerido por ley o proceso judicial, específicamente incluyendo tribunales en el Condado de Okaloosa, Florida, para proteger nuestros derechos o los derechos de otros, o para hacer cumplir nuestros Términos y Condiciones.",
    privacySharingItem3: "Transferencias de Negocio: Si Apex Vista AI está involucrada en una fusión, adquisición o venta de activos, tus datos pueden ser transferidos como parte de esa transacción.",
    privacyRights: "6. Tus Derechos y Opciones",
    privacyRightsItem1: "Acceso y Corrección: Puedes revisar y actualizar la mayoría de la información de tu cuenta directamente en tu panel de control.",
    privacyRightsItem2: "Cancelación de Marketing: Puedes cancelar la suscripción a correos de marketing en cualquier momento.",
    privacyRightsItem3: "Eliminación de Datos (Derecho al Olvido): Puedes solicitar que eliminemos tu cuenta y datos asociados, sujeto a períodos de retención obligatorios para propósitos legales, fiscales o regulatorios.",
    privacySecurity: "7. Seguridad de Datos",
    privacySecurityText: "Implementamos medidas de seguridad físicas, técnicas y administrativas razonables diseñadas para proteger tu Información Personal. Eres responsable de mantener la confidencialidad de la contraseña de tu cuenta.",
    privacyChildren: "8. Privacidad de Menores",
    privacyChildrenText: "Nuestro Servicio no está dirigido a individuos menores de 18 años. No recopilamos conscientemente información personal de menores de 18 años.",
    privacyChanges: "9. Cambios en esta Política de Privacidad",
    privacyChangesText: "El Proveedor tiene la discreción de actualizar esta Política de Privacidad en cualquier momento. Te notificaremos de cualquier cambio material publicando la nueva política en nuestro sitio web o a través de una notificación por correo electrónico.",

    // Pricing Page
    pricingTitle: "Precios Bajos, Simples y Poderosos",
    pricingSubtitle: "Elige la solución perfecta para tu negocio. Comienza con nuestra plataforma principal u obtén desarrollo personalizado adaptado a tus necesidades.",
    coreSolutionTitle: "La Solución Principal",
    coreSolutionSubtitle: "Todo lo que necesitas para automatizar y escalar tu negocio con IA",
    reachBoosterTitle: "Plan Reach Booster",
    reachBoosterSubtitle: "Perfecto para emprendedores individuales, propietarios de pequeñas empresas y micro-agencias",
    mostPopular: "MÁS POPULAR",
    perMonth: "por mes",
    perYear: "por año",
    saveMonths: "¡Ahorra 2 meses!",
    coreAIAccess: "Acceso Principal a IA",
    featuresSupport: "Características y Soporte",
    subscribeNow: "Suscríbete Ahora y Comienza a Automatizar →",
    moneyBackGuarantee: "Garantía de devolución de dinero de 30 días • Cancela en cualquier momento",
    premiumDevelopmentTitle: "Desarrollo Premium Bajo Demanda",
    premiumDevelopmentSubtitle: "Obtén desarrollo personalizado y tiempo 1:1 con nuestro equipo experto. La única manera de obtener soluciones completamente adaptadas a tus necesidades comerciales únicas.",
    apexSolutionTitle: "Construcción de Solución Apex",
    apexSolutionPrice: "Desde $1,500",
    oneTimeFee: "(Tarifa única)",
    apexSolutionDesc: "Desarrollo de Producto Inicial: Planificamos, construimos e implementamos una herramienta digital completamente nueva y personalizada usando nuestro motor de IA avanzado.",
    featureEnhancementTitle: "Mejora de Características",
    featureEnhancementPrice: "$400 - $1,200",
    featureEnhancementDesc: "Desarrollo de Actualizaciones: Agrega características personalizadas a tu plataforma Reach Booster existente, como integraciones de API específicas o informes propietarios.",
    requestCustomQuote: "Solicitar Cotización Personalizada",
    fullName: "Nombre Completo *",
    emailAddress: "Dirección de Correo Electrónico *",
    companyName: "Nombre de la Empresa",
    projectDetails: "Detalles del Proyecto *",
    projectDetailsPlaceholder: "Describe los requisitos de tu proyecto, objetivos, cronograma y cualquier característica específica que necesites...",
    requestQuote: "Solicitar Cotización Personalizada →",
    sendingRequest: "Enviando Solicitud...",
    responseTime: "Tiempo de Respuesta:",
    responseTimeDesc: "Las cotizaciones personalizadas se proporcionan típicamente dentro de 48 horas. Los proyectos complejos pueden requerir una breve llamada de consulta.",
    faqTitle: "Preguntas Frecuentes",
    freeConsultationTitle: "Sesión de Estrategia de IA GRATUITA",
    freeConsultationDesc: "Obtén una sesión personalizada de 30 minutos para entender las posibilidades del Motor Apex Vista AI para tu negocio específico.",
    bookConsultation: "Reserva Tu Consulta Gratuita →",
    bookingSession: "Reservando Tu Sesión...",
    backToHome: "Volver al Inicio",

    // Contact Page
    contactTitle: "Ponte en Contacto",
    contactSubtitle: "¿Listo para transformar tu presencia digital? Hablemos sobre cómo podemos ayudar a tu negocio a crecer con nuestras soluciones de plataforma impulsadas por IA.",
    contactInformation: "Información de Contacto",
    phone: "Teléfono",
    phoneAvailable: "Disponible Lunes - Viernes, 9 AM - 6 PM EST",
    emailResponse: "Responderemos en 24 horas",
    locationClick: "Haz clic para ver nuestra ubicación",
    socialMedia: "Redes Sociales",
    followUs: "Síguenos para actualizaciones e insights",
    businessHours: "Horario Comercial",
    mondayFriday: "Lunes - Viernes",
    saturday: "Sábado",
    sunday: "Domingo",
    closed: "Cerrado",
    happyClients: "Clientes Satisfechos",
    projectsDelivered: "Proyectos Entregados",
    sendMessage: "Envíanos un Mensaje",
    yourFullName: "Tu nombre completo",
    yourEmail: "tu@email.com",
    companyOptional: "Nombre de tu empresa (opcional)",
    messageLabel: "Mensaje *",
    messagePlaceholder: "Cuéntanos sobre tu proyecto, objetivos o cualquier pregunta que tengas...",
    sendMessageBtn: "Enviar Mensaje →",
    sendingMessage: "Enviando Mensaje...",
    responseTimeContact: "Típicamente respondemos dentro de 24 horas durante los días hábiles. Para asuntos urgentes, llámanos directamente."
  }
}

// Language provider component
interface LanguageProviderProps {
  children: ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>('en')
  const [isClient, setIsClient] = useState(false)

  // Load language from localStorage on mount
  useEffect(() => {
    setIsClient(true)
    try {
      const savedLanguage = localStorage.getItem('language') as Language
      if (savedLanguage && ['en', 'pt', 'es'].includes(savedLanguage)) {
        setLanguageState(savedLanguage)
      }
    } catch (error) {
      console.warn('Failed to load language from localStorage:', error)
    }
  }, [])

  // Save language to localStorage when changed
  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    if (isClient) {
      try {
        localStorage.setItem('language', lang)
      } catch (error) {
        console.warn('Failed to save language to localStorage:', error)
      }
    }
  }

  // Translation function
  const t = (key: string): string => {
    try {
      return translations[language][key as keyof typeof translations[typeof language]] || key
    } catch (error) {
      console.warn('Translation error for key:', key, error)
      return key
    }
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

// Hook to use language context
export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}